version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Runs once a week to keep noise down (can be "daily" or "monthly")
      interval: "weekly"
    
    ignore:
      # Ttells Dependabot to ignore ALL major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
    # Groups all minor/patch updates into a single PR
    groups:
      dependencies:
        patterns:
          - "*"